require 'date'

Offer.delete_all
User.delete_all

users = [
  { first_name: 'John', last_name: 'Doe', birth_date: Date.new(1980, 1, 1), rating: 3.5, email: 'john.doe@example.com', password: 'password123' },
  { first_name: 'Jane', last_name: 'Doe', birth_date: Date.new(1990, 2, 1), rating: 4.2, email: 'jane.doe@example.com', password: 'password123' },
  { first_name: 'Alice', last_name: 'Smith', birth_date: Date.new(1985, 3, 1), rating: 4.8, email: 'alice.smith@example.com', password: 'password123' },
  { first_name: 'Bob', last_name: 'Johnson', birth_date: Date.new(1975, 4, 1), rating: 2.9, email: 'bob.johnson@example.com', password: 'password123' },
  { first_name: 'Carlos', last_name: 'Garcia', birth_date: Date.new(1982, 5, 1), rating: 4.4, email: 'carlos.garcia@example.com', password: 'password123' },
  { first_name: 'Diana', last_name: 'Martinez', birth_date: Date.new(1988, 6, 1), rating: 4.7, email: 'diana.martinez@example.com', password: 'password123' },
  { first_name: 'Ewa', last_name: 'Hernandez', birth_date: Date.new(1983, 7, 1), rating: 3.3, email: 'ewa.hernandez@example.com', password: 'password123' },
  { first_name: 'François', last_name: 'Lopez', birth_date: Date.new(1979, 8, 1), rating: 4.1, email: 'francois.lopez@example.com', password: 'password123' },
  { first_name: 'Giorgio', last_name: 'Wilson', birth_date: Date.new(1981, 9, 1), rating: 4.9, email: 'giorgio.wilson@example.com', password: 'password123' },
  { first_name: 'Hana', last_name: 'Anderson', birth_date: Date.new(1987, 10, 1), rating: 3.6, email: 'hana.anderson@example.com', password: 'password123' },
  { first_name: 'Igor', last_name: 'Thomas', birth_date: Date.new(1976, 11, 1), rating: 4.3, email: 'igor.thomas@example.com', password: 'password123' },
  { first_name: 'Jasmine', last_name: 'Taylor', birth_date: Date.new(1989, 12, 1), rating: 4.8, email: 'jasmine.taylor@example.com', password: 'password123' },
  { first_name: 'Ken', last_name: 'Moore', birth_date: Date.new(1984, 1, 1), rating: 2.5, email: 'ken.moore@example.com', password: 'password123' },
  { first_name: 'Lina', last_name: 'Jackson', birth_date: Date.new(1978, 2, 1), rating: 4.2, email: 'lina.jackson@example.com', password: 'password123' },
  { first_name: 'Marta', last_name: 'Martin', birth_date: Date.new(1986, 3, 1), rating: 3.9, email: 'marta.martin@example.com', password: 'password123' },
  { first_name: 'Nils', last_name: 'Lee', birth_date: Date.new(1980, 4, 1), rating: 4.7, email: 'nils.lee@example.com', password: 'password123' },
  { first_name: 'Olga', last_name: 'Perez', birth_date: Date.new(1983, 5, 1), rating: 2.8, email: 'olga.perez@example.com', password: 'password123' },
  { first_name: 'Pedro', last_name: 'Thompson', birth_date: Date.new(1977, 6, 1), rating: 4.4, email: 'pedro.thompson@example.com', password: 'password123' },
  { first_name: 'Quinn', last_name: 'White', birth_date: Date.new(1982, 7, 1), rating: 3.2, email: 'quinn.white@example.com', password: 'password123' },
  { first_name: 'Rita', last_name: 'Harris', birth_date: Date.new(1979, 8, 1), rating: 4.5, email: 'rita.harris@example.com', password: 'password123' },
  { first_name: 'Sam', last_name: 'Sanchez', birth_date: Date.new(1981, 9, 1), rating: 2.9, email: 'sam.sanchez@example.com', password: 'password123' },
  { first_name: 'Tina', last_name: 'Clark', birth_date: Date.new(1984, 10, 1), rating: 4.3, email: 'tina.clark@example.com', password: 'password123' },
  { first_name: 'Ugo', last_name: 'Ramirez', birth_date: Date.new(1978, 11, 1), rating: 4.7, email: 'ugo.ramirez@example.com', password: 'password123' },
  { first_name: 'Vera', last_name: 'Lewis', birth_date: Date.new(1987, 12, 1), rating: 3.4, email: 'vera.lewis@example.com', password: 'password123' },
  { first_name: 'Wang', last_name: 'Robinson', birth_date: Date.new(1980, 1, 1), rating: 4.1, email: 'wang.robinson@example.com', password: 'password123' },
  { first_name: 'Xia', last_name: 'Walker', birth_date: Date.new(1985, 2, 1), rating: 4.6, email: 'xia.walker@example.com', password: 'password123' },
  { first_name: 'Yuki', last_name: 'Young', birth_date: Date.new(1976, 3, 1), rating: 2.7, email: 'yuki.young@example.com', password: 'password123' },
  { first_name: 'Zara', last_name: 'Allen', birth_date: Date.new(1988, 4, 1), rating: 4.2, email: 'zara.allen@example.com', password: 'password123' },
  { first_name: 'John', last_name: 'Doe', birth_date: Date.new(1980, 1, 1), rating: 3.5, email: 'john.doe2@example.com', password: 'password123' },
  { first_name: 'Jane', last_name: 'Doe', birth_date: Date.new(1990, 2, 1), rating: 4.2, email: 'jane.doe2@example.com', password: 'password123' },
  { first_name: 'Alice', last_name: 'Smith', birth_date: Date.new(1985, 3, 1), rating: 4.8, email: 'alice.smith2@example.com', password: 'password123' },
  { first_name: 'Bob', last_name: 'Johnson', birth_date: Date.new(1975, 4, 1), rating: 2.9, email: 'bob.johnson2@example.com', password: 'password123' },
]

users.each do |user|
  User.create!(user)
end

offers = [
    { brand: 'Ford', model: 'Mustang', year: 1967, km: 120_000, user: User.first, price: 350, address: '123 Rue de Rivoli, Paris, France', description: 'Classic car with great history.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Chevrolet', model: 'Camaro', year: 1969, km: 80_000, user: User.second, price: 400, address: '45 Avenue des Frères Lumière, Lyon, France', description: 'Vintage Camaro, well maintained.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Dodge', model: 'Charger', year: 1970, km: 90_000, user: User.third, price: 450, address: '78 Boulevard Michelet, Marseille, France', description: 'Powerful Charger, a true classic.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Ferrari', model: '308 GTS', year: 1978, km: 50_000, user: User.fourth, price: 900, address: '22 Promenade des Anglais, Nice, France', description: 'Luxury Ferrari in excellent condition.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Porsche', model: '911', year: 1985, km: 70_000, user: User.fifth, price: 700, address: '50 Rue Sainte-Catherine, Bordeaux, France', description: 'Iconic Porsche 911, well preserved.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'BMW', model: 'M3', year: 1988, km: 60_000, user: User.find_by(email: 'ewa.hernandez@example.com'), price: 600, address: '33 Rue Faidherbe, Lille, France', description: 'Classic BMW M3, great performance.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Mercedes-Benz', model: '190E', year: 1990, km: 110_000, user: User.find_by(email: 'francois.lopez@example.com'), price: 550, address: '12 Rue du Vieux Marché aux Poissons, Strasbourg, France', description: 'Reliable 190E, smooth ride.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Jaguar', model: 'E-Type', year: 1965, km: 40_000, user: User.find_by(email: 'giorgio.wilson@example.com'), price: 800, address: '7 Rue de la Fosse, Nantes, France', description: 'Vintage Jaguar, well maintained.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Toyota', model: 'Supra', year: 1994, km: 100_000, user: User.find_by(email: 'hana.anderson@example.com'), price: 500, address: '99 Allées Jean Jaurès, Toulouse, France', description: 'Sporty Supra, great condition.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Nissan', model: 'Skyline GT-R', year: 1995, km: 95_000, user: User.find_by(email: 'igor.thomas@example.com'), price: 600, address: '4 Rue de Université, Montpellier, France', description: 'Classic GT-R, powerful performance.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Mazda', model: 'RX-7', year: 1993, km: 85_000, user: User.find_by(email: 'jasmine.taylor@example.com'), price: 550, address: '21 Rue Saint-Georges, Rennes, France', description: 'Well-kept RX-7, fun to drive.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Ford', model: 'Thunderbird', year: 1957, km: 150_000, user: User.find_by(email: 'ken.moore@example.com'), price: 700, address: '10 Place du Forum, Reims, France', description: 'Classic Thunderbird, stylish ride.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Chevrolet', model: 'Corvette', year: 1963, km: 65_000, user: User.find_by(email: 'lina.jackson@example.com'), price: 750, address: '3 Quai Southampton, Le Havre, France', description: 'Vintage Corvette, well preserved.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Volkswagen', model: 'Beetle', year: 1972, km: 130_000, user: User.find_by(email: 'marta.martin@example.com'), price: 300, address: '15 Rue des Armuriers, Saint-Étienne, France', description: 'Classic Beetle, reliable car.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Fiat', model: '500', year: 1967, km: 55_000, user: User.find_by(email: 'nils.lee@example.com'), price: 350, address: '27 Rue Jean Jaurès, Toulon, France', description: 'Classic Fiat 500, great condition.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Lamborghini', model: 'Countach', year: 1982, km: 40_000, user: User.find_by(email: 'olga.perez@example.com'), price: 1200, address: '14 Rue des Arènes, Angers, France', description: 'Iconic Countach, excellent condition.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Alfa Romeo', model: 'Spider', year: 1974, km: 75_000, user: User.find_by(email: 'pedro.thompson@example.com'), price: 500, address: '8 Rue de la République, Grenoble, France', description: 'Classic Spider, fun convertible.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Aston Martin', model: 'DB5', year: 1964, km: 50_000, user: User.find_by(email: 'quinn.white@example.com'), price: 1000, address: '2 Rue de la Liberté, Dijon, France', description: 'Classic DB5, elegant and powerful.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Maserati', model: 'Ghibli', year: 1970, km: 45_000, user: User.find_by(email: 'rita.harris@example.com'), price: 900, address: '39 Rue de Horloge, Nîmes, France', description: 'Vintage Ghibli, well maintained.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Lotus', model: 'Esprit', year: 1987, km: 60_000, user: User.find_by(email: 'sam.sanchez@example.com'), price: 600, address: '18 Rue de Siam, Brest, France', description: 'Classic Esprit, sporty and sleek.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Renault', model: '5 Turbo', year: 1980, km: 85_000, user: User.find_by(email: 'tina.clark@example.com'), price: 450, address: '42 Rue Jean Jaurès, Limoges, France', description: 'Vintage 5 Turbo, fun to drive.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Peugeot', model: '205 GTI', year: 1987, km: 95_000, user: User.find_by(email: 'ugo.ramirez@example.com'), price: 400, address: '11 Place Gambetta, Amiens, France', description: 'Classic 205 GTI, great condition.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Citroën', model: '2CV', year: 1970, km: 110_000, user: User.find_by(email: 'vera.lewis@example.com'), price: 300, address: '20 Rue du Faubourg Saint-Antoine, Paris, France', description: 'Classic Citroën 2CV, reliable.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Saab', model: '900 Turbo', year: 1986, km: 105_000, user: User.find_by(email: 'wang.robinson@example.com'), price: 450, address: '6 Rue du Vieux-Port, Marseille, France', description: 'Reliable 900 Turbo, great performance.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Volvo', model: 'P1800', year: 1964, km: 90_000, user: User.find_by(email: 'xia.walker@example.com'), price: 500, address: '34 Rue du Mont Blanc, Grenoble, France', description: 'Vintage P1800, well preserved.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Honda', model: 'NSX', year: 1991, km: 70_000, user: User.find_by(email: 'yuki.young@example.com'), price: 650, address: '28 Avenue Jean Jaurès, Lyon, France', description: 'Sporty NSX, well maintained.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Subaru', model: 'Impreza WRX', year: 1999, km: 120_000, user: User.find_by(email: 'zara.allen@example.com'), price: 500, address: '56 Rue Nationale, Lille, France', description: 'Classic WRX, powerful and fun.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Mitsubishi', model: 'Lancer Evo', year: 1998, km: 115_000, user: User.find_by(email: 'john.doe2@example.com'), price: 550, address: '9 Rue des Fleurs, Nice, France', description: 'Iconic Lancer Evo, well kept.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Acura', model: 'Integra', year: 1997, km: 100_000, user: User.find_by(email: 'jane.doe2@example.com'), price: 450, address: '3 Rue de la Gare, Toulouse, France', description: 'Sporty Integra, reliable and fun.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Ferrari', model: 'F40', year: 1989, km: 40_000, user: User.find_by(email: 'alice.smith2@example.com'), price: 1500, address: '14 Rue des Écoles, Montpellier, France', description: 'Legendary Ferrari F40, excellent.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'McLaren', model: 'F1', year: 1995, km: 30_000, user: User.find_by(email: 'bob.johnson2@example.com'), price: 2000, address: '7 Rue du Faubourg Saint-Honoré, Paris, France', description: 'Rare McLaren F1, top condition.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Bugatti', model: 'EB110', year: 1991, km: 25_000, user: User.find_by(email: 'john.doe@example.com'), price: 1800, address: '5 Avenue des Champs-Élysées, Paris, France', description: 'Iconic Bugatti EB110, pristine.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Rolls-Royce', model: 'Silver Shadow', year: 1975, km: 80_000, user: User.find_by(email: 'jane.doe@example.com'), price: 800, address: '23 Rue de la Paix, Paris, France', description: 'Luxury Silver Shadow, well kept.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Bentley', model: 'Continental', year: 1955, km: 100_000, user: User.find_by(email: 'alice.smith@example.com'), price: 850, address: '19 Rue du Bac, Paris, France', description: 'Classic Bentley, luxurious ride.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Cadillac', model: 'Eldorado', year: 1959, km: 150_000, user: User.find_by(email: 'bob.johnson@example.com'), price: 750, address: '11 Rue de la Bourse, Lyon, France', description: 'Iconic Eldorado, well maintained.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Lincoln', model: 'Continental', year: 1961, km: 140_000, user: User.find_by(email: 'carlos.garcia@example.com'), price: 700, address: '25 Rue de la République, Marseille, France', description: 'Classic Continental, smooth ride.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Oldsmobile', model: '442', year: 1968, km: 85_000, user: User.find_by(email: 'diana.martinez@example.com'), price: 600, address: '30 Rue Victor Hugo, Nantes, France', description: 'Powerful 442, well preserved.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Pontiac', model: 'GTO', year: 1966, km: 90_000, user: User.find_by(email: 'ewa.hernandez@example.com'), price: 650, address: '17 Rue Franklin, Grenoble, France', description: 'Classic GTO, great condition.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Plymouth', model: 'Barracuda', year: 1971, km: 70_000, user: User.find_by(email: 'francois.lopez@example.com'), price: 700, address: '14 Place Bellecour, Lyon, France', description: 'Iconic Barracuda, well kept.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'AMC', model: 'Javelin', year: 1970, km: 110_000, user: User.find_by(email: 'giorgio.wilson@example.com'), price: 500, address: '22 Rue de la Paix, Paris, France', description: 'Classic Javelin, reliable performance.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Datsun', model: '240Z', year: 1971, km: 65_000, user: User.find_by(email: 'hana.anderson@example.com'), price: 600, address: '5 Rue de la Monnaie, Lille, France', description: 'Sporty 240Z, great condition.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Triumph', model: 'TR6', year: 1974, km: 95_000, user: User.find_by(email: 'igor.thomas@example.com'), price: 450, address: '10 Avenue Jean Médecin, Nice, France', description: 'Classic TR6, fun to drive.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'MG', model: 'MGB', year: 1965, km: 120_000, user: User.find_by(email: 'jasmine.taylor@example.com'), price: 400, address: '16 Rue des Minimes, Toulouse, France', description: 'Vintage MGB, well maintained.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Austin', model: 'Mini Cooper', year: 1967, km: 100_000, user: User.find_by(email: 'ken.moore@example.com'), price: 350, address: '8 Rue Saint-Dominique, Paris, France', description: 'Classic Mini Cooper, stylish ride.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'DeLorean', model: 'DMC-12', year: 1981, km: 50_000, user: User.find_by(email: 'lina.jackson@example.com'), price: 1000, address: '4 Place Saint-Sulpice, Paris, France', description: 'Legendary DeLorean, excellent.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Lancia', model: 'Stratos', year: 1974, km: 55_000, user: User.find_by(email: 'marta.martin@example.com'), price: 900, address: '29 Rue de Rennes, Paris, France', description: 'Classic Stratos, well preserved.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Iso', model: 'Grifo', year: 1972, km: 60_000, user: User.find_by(email: 'nils.lee@example.com'), price: 850, address: '12 Rue de Rivoli, Paris, France', description: 'Vintage Grifo, stylish and fast.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) },
    { brand: 'Shelby', model: 'Cobra', year: 1966, km: 30_000, user: User.find_by(email: 'olga.perez@example.com'), price: 1200, address: '6 Rue de Seine, Paris, France', description: 'Legendary Shelby Cobra, powerful.', availability_start: start_date = Date.today + rand(1..60), availability_end: start_date + rand(30..90) }
  ]


offers.each do |offer|
  Offer.create!(offer)
end
